// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNMuwbws4AIZPAoyePPCsBV9buMJk9nSE',
    appId: '1:1095507577125:web:286dff487c9016081472cc',
    messagingSenderId: '1095507577125',
    projectId: 'glycosync-d82bf',
    authDomain: 'glycosync-d82bf.firebaseapp.com',
    storageBucket: 'glycosync-d82bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Pq3fZ5NOcq071AxP-7r46-OUMqa8ZjE',
    appId: '1:1095507577125:android:12a482e3b9c72ef31472cc',
    messagingSenderId: '1095507577125',
    projectId: 'glycosync-d82bf',
    storageBucket: 'glycosync-d82bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlIj2NOdAV0mC9DcIVrWIqn1rZVOKVpw',
    appId: '1:1095507577125:ios:3306fd1c8b449a4e1472cc',
    messagingSenderId: '1095507577125',
    projectId: 'glycosync-d82bf',
    storageBucket: 'glycosync-d82bf.firebasestorage.app',
    iosClientId: '1095507577125-041tribbl3p92vgaohb1gtrmkas942dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.glycosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlIj2NOdAV0mC9DcIVrWIqn1rZVOKVpw',
    appId: '1:1095507577125:ios:3306fd1c8b449a4e1472cc',
    messagingSenderId: '1095507577125',
    projectId: 'glycosync-d82bf',
    storageBucket: 'glycosync-d82bf.firebasestorage.app',
    iosClientId: '1095507577125-041tribbl3p92vgaohb1gtrmkas942dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.glycosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNMuwbws4AIZPAoyePPCsBV9buMJk9nSE',
    appId: '1:1095507577125:web:f1cb15030fbd24df1472cc',
    messagingSenderId: '1095507577125',
    projectId: 'glycosync-d82bf',
    authDomain: 'glycosync-d82bf.firebaseapp.com',
    storageBucket: 'glycosync-d82bf.firebasestorage.app',
  );
}
